<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>estrutura do-while- caso uso-curso php </title>
</head>
<body>

<?php
if(isset($_POST["dependentes"]))
 $dependentes = $_POST["dependentes"]



?>





<table border="1">
    <tr>
       <th></th>
        <th>NOME</th>
        <th>NASC</th>

    </tr>
    <tr>
        <td>DEPENDENTE</td>
        <td><input type="text" name="nome"></td>
        <td><input type="text" name="nasc"></td>


    </tr>






</table>


<form method="post">
    <input type="text" name="dependetes">

    <input type="submit">

</form>














</body>
</html>